# --- PHOENIX PROJECT: GLOBAL CONFIGURATION (M5 MODE) ---

# FINANCIERO (CFO RULES)
CAPITAL_INICIAL = 200.0
RIESGO_POR_OPERACION = 0.01  # 1% Estricto
DRAWDOWN_MAXIMO_DIARIO = 0.03 
TARGET_DIARIO = 0.03         

# TRADING PARAMS
SYMBOL = "XAUUSD"
TIMEFRAME = "M5" # <--- CAMBIADO A M5
SPREAD_MAXIMO = 0.30  

# AI MODEL PARAMS
LOOKBACK_WINDOW = 60  # 5 horas de contexto histórico
HIDDEN_LAYERS = [128, 64, 32]
LEARNING_RATE = 0.001
EPOCHS = 100

# RUTAS
DATA_RAW = "vantage_gold.csv"
MODEL_SAVE_PATH = "phoenix_brain.pth"